services:
  backend:
    build:
      context: ./currency-converter-backend/CurrencyConverter.Api/CurrencyConverter.Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./currency-converter-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    volumes:
      - ./currency-converter-frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
